### ISSUE TITLE
Support for multiple scopes

### ISSUE THREAD

**Issue by msiostrom** [haribert/sal-ActiveDirectory#1]
Hi,

Thank you for this awesome code.

Would you consider adding support for multiple search scope (for example, via LDAPSearchUnion)?

**Comment by haribert** [comment]
Hi

Thanks for your feedback.

Do you mean multiple search scope for authentication or authorization?

Authentication (`AUTH_LDAP_USER_SEARCH`) is not planned, because our organisation does not have multiple places where the users are. Therefore we are not able to test it. Nevertheless, a similar approach as used in `AUTH_LDAP_USER_PROFILE ` or `AUTH_LDAP_USER_TO_BUSINESS_UNIT ` (where you can specify multiple groups as a tuple) should be easy to implement.

For authorization (`AUTH_LDAP_USER_PROFILE ` and `AUTH_LDAP_USER_TO_BUSINESS_UNIT `) I already mentioned it. It is possible to specify multiple AD/LDAP groups as a tuple.

**Comment by msiostrom** [comment]
Hi Haribert,

I mean something like this:

`AUTH_LDAP_USER_SEARCH = ('DC=eu,DC=company,DC=corp','DC=us,DC=company,DC=corp')`

With LDAPSearchUnion, this would look like this:
```
AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
    LDAPSearch("DC=eu,DC=company,DC=corp", ldap.SCOPE_SUBTREE, "(sAMAccountName=%s)"),
    LDAPSearch("DC=us,DC=company,DC=corp", ldap.SCOPE_SUBTREE, "(sAMAccountName=%s)"),
)
```

This would in theory allow you to specify a group at `AUTH_LDAP_USER_PROFILE` with users from multiple domains.

I understand if this is not in the scope of your project, I just thought I'd ask in case it is something trivial for you to add.

**Comment by haribert** [comment]
@msiostrom Can you please test my branch dev_1.0.1. I do not have the infrastructure to test several groups.

I just implemented it the way I think it should work.  If you tell me, that it is working, I can merge it to the master branch. Afterwards, the code will be moved to the sal repository.

**Comment by msiostrom** [comment]
@haribert Apologies for my delayed response.

Nice work! I think you are really close to making it work!

I noticed an issue with specifying `AUTH_LDAP_USER_DOMAIN = 'company.com'`

When a user from the xx subdomain signs in, you need to set this variable to `AUTH_LDAP_USER_DOMAIN = 'xx.company.com'`. If you don't do this, the connector will try to sign in as `username@company.com` instead of `username@ee.company.com` which will fail.

One simple way to solve this would be to allow an array to be specified at AUTH_LDAP_USER_DOMAIN and loop trough the domains until user gets authenticated.

**Comment by haribert** [comment]
@msiostrom Can you please test my latest commit with the multiple AUTH_LDAP_USER_DOMAIN?
Hope this is the last change, to work with different subdomains.

Furthermore, I will not change anything concerning empty attributes in AD.

**Comment by msiostrom** [comment]
@haribert I'm unfortunatelly not able to make it work. Maybe we should skip this feature in favour of your original code so you can move on with more important things :)

**Comment by haribert** [comment]
ok, I reverted the commits.

Can I close this issue?

**Comment by msiostrom** [comment]
Yes please
